# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec file for HT Proxy Backend
# Build: pyinstaller backend.spec

import os

block_cipher = None

# Các file data cần đưa vào bundle
datas = [
    ('.env', '.'),
    ('firebase-key.json', '.'),
    ('routers', 'routers'),
]

# Hidden imports cần thiết cho FastAPI + firebase-admin
hidden_imports = [
    'uvicorn',
    'uvicorn.config',
    'uvicorn.main',
    'uvicorn.server',
    'uvicorn.lifespan',
    'uvicorn.lifespan.on',
    'uvicorn.protocols',
    'uvicorn.protocols.http',
    'uvicorn.protocols.http.auto',
    'uvicorn.protocols.http.h11_impl',
    'uvicorn.protocols.websockets',
    'uvicorn.protocols.websockets.auto',
    'uvicorn.loops',
    'uvicorn.loops.auto',
    'uvicorn.loops.asyncio',
    'fastapi',
    'pydantic',
    'pydantic_settings',
    'passlib',
    'passlib.handlers',
    'passlib.handlers.bcrypt',
    'passlib.handlers.sha2_crypt',
    'jose',
    'jose.jwt',
    'jose.algorithms',
    'multipart',
    'firebase_admin',
    'firebase_admin.credentials',
    'firebase_admin.firestore',
    'firebase_admin.auth',
    'google.cloud.firestore',
    'google.cloud.firestore_v1',
    'google.auth',
    'google.auth.transport',
    'google.auth.transport.requests',
    'google.oauth2',
    'google.oauth2.service_account',
    'email_validator',
    'RouterOS_api',
    'routeros_api',
    'routeros_api.api',
    'routeros_api.api_communicator',
    'routeros_api.api_structure',
    'routeros_api.sentence',
    'httpx',
    'httpx._transports',
    'httpx._transports.default',
    'requests',
    'requests.adapters',
    'requests.sessions',
    'urllib3',
    'urllib3.util',
    'urllib3.util.retry',
    'urllib3.util.ssl_',
    'urllib3.contrib',
    'socksio',
    'anyio',
    'anyio._backends._asyncio',
    'starlette',
    'starlette.middleware',
    'starlette.middleware.cors',
    'h11',
    # App modules
    'main',
    'config',
    'auth',
    'firebase_app',
    'quick_db',
    'schemas',
    'mikrotik_client',
    'routers.proxy_router',
    'routers.settings_router',
    'routers.apikey_router',
    'routers.check_router',
    'routers.admin_router',
    'routers.quick_router',
]

a = Analysis(
    ['launcher.py'],
    pathex=['.'],
    binaries=[],
    datas=datas,
    hiddenimports=hidden_imports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['tkinter', 'matplotlib', 'numpy', 'PIL', 'cv2'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,         # KHÔNG có console window
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
